/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CarRentalDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bill;
import model.Car;
import model.CarRental;

/**
 *
 * @author ADMIN
 */
public class CarRentalFrm extends javax.swing.JFrame {
    private Bill bill;
    private ArrayList<CarRental> listCarRental = new ArrayList<>();
    private DefaultTableModel tmCarRental;
    private ArrayList<CarRental> listCarRentalChoosed = new ArrayList<>();
    /**
     * Creates new form CarRentalFrm
     */
    public CarRentalFrm(Bill bill) throws SQLException {
        this.bill = bill;
        initComponents();
        tmCarRental = (DefaultTableModel) tblCarRental.getModel();
        tmCarRental.setRowCount(0);
        listCarRental.addAll(new CarRentalDAO().showCarRentalInContract(bill.getContract().getId()));             
        for (CarRental c : listCarRental) {
            tmCarRental.addRow(c.toObjects());              
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarRental = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCarRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã xe", "Hãng xe", "Dòng xe", "Biển số xe", "Ngày thuê", "Ngày trả", "Thành tiền", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarRental);

        jLabel1.setText("CarRental");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(448, 448, 448))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(444, 444, 444))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        for(int row = 0; row < tblCarRental.getRowCount(); row++){
            if(tblCarRental.getValueAt(row, 7) != null){                  
                Boolean checked = (Boolean) tblCarRental.getValueAt(row, 7);
                if(checked){
                    try {
                        Car car = new Car();
                        car.setId(tblCarRental.getValueAt(row, 0).toString());
                        car.setManufacturer(tblCarRental.getValueAt(row, 1).toString());
                        car.setType(tblCarRental.getValueAt(row, 2).toString());
                        car.setNumberPlate(tblCarRental.getValueAt(row, 3).toString());
                        CarRental carRental = new CarRental();
                        carRental.setDayStart(new SimpleDateFormat("dd-MM-yyyy").parse(tblCarRental.getValueAt(row, 4).toString()));
                        carRental.setDayEnd(new SimpleDateFormat("dd-MM-yyyy").parse(tblCarRental.getValueAt(row, 5).toString()));
                        carRental.setTotalAmount(Float.parseFloat(tblCarRental.getValueAt(row, 6).toString()));
                        carRental.setCar(car);
                        listCarRentalChoosed.add(carRental);
                    } catch (ParseException ex) {
                        Logger.getLogger(CarRentalFrm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        if(listCarRentalChoosed.size() == 0){
            JOptionPane.showMessageDialog(this, "Hay chon xe de tra");
        }
        else{
            (new InvoiceFrm(bill, listCarRentalChoosed)).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRentalFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRentalFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRentalFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRentalFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarRental;
    // End of variables declaration//GEN-END:variables
}
