/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Bill;
import model.CarRental;
import model.FailureDetail;
import model.MortgageDetail;

/**
 *
 * @author ADMIN
 */
public class InvoiceFrm extends javax.swing.JFrame {
    private Bill bill;
    private ArrayList<CarRental> listCarRentalChoosed;
    private ArrayList<MortgageDetail> listMortgageDetailChoosed;
    private MortgageFrm GDMortgage;
    /**
     * Creates new form InvoiceFrm
     */
    public InvoiceFrm(Bill bill, ArrayList<CarRental> listCarRentalChoosed) {
        this.bill = bill;
        this.listCarRentalChoosed = listCarRentalChoosed;
        initComponents();
        set();
    }
    
    private InvoiceFrm(){
        initComponents();
        set();
    }
    
    public void updateMortgageDetail(ArrayList<MortgageDetail> listMortgageDetail){
        this.listMortgageDetailChoosed = listMortgageDetail;
        set();
    }
    
    private float updateMortgageText(){
        if(this.listMortgageDetailChoosed == null || this.listMortgageDetailChoosed.size() == 0) return 0;
        float deposit = 0;
        txtBill.append("\nTai san dam bao:");
        for(MortgageDetail m : this.listMortgageDetailChoosed){         
            txtBill.append("\n+ " + m.getQuantity() + " " + m.getMortgage().getName());
            if(m.getMortgage().getId().equalsIgnoreCase("M3")){
                deposit = m.getQuantity();
            }
        }
        return deposit;
    }
    
    private float updateFailureDetailText(CarRental carRental){
        
        if(carRental.getFailures() == null || carRental.getFailures().size() == 0) return 0;
        float compensation = 0;
        txtBill.append("\n***Hong hoc: ");
        for(FailureDetail f : carRental.getFailures()){
            txtBill.append("\n- " + f.getFailure().getName() + " - " + f.getQuantity());
            txtBill.append("\n->Tien den bu: " + f.getTotalCompensation());
            compensation += f.getTotalCompensation();
        }
        return compensation;
    }
    
    public void set(){
        String firstLine = txtBill.getText().split("\n", 2)[0];
        txtBill.setText(firstLine);
        float totalAmount = 0;
        txtBill.append("\nMa hop dong: " + bill.getContract().getId());
        txtBill.append("\nTen khach hang: " + bill.getContract().getClient().getName());
        txtBill.append("\nDia chi: " + bill.getContract().getClient().getAddress());
        txtBill.append("\nSo dien thoai: " + bill.getContract().getClient().getTel());
        txtBill.append("\nDanh sach xe khach hang ban giao:");
        for(CarRental c : listCarRentalChoosed){
            float compensation = 0;
            txtBill.append("\n-" + c.getCar().getId());
            txtBill.append("\n+Hang xe: " + c.getCar().getManufacturer());
            txtBill.append("\n+Dong xe: " + c.getCar().getType());
            txtBill.append("\n+Bien so xe: " + c.getCar().getNumberPlate());
            txtBill.append("\n+Ngay thue: " + new SimpleDateFormat("dd-MM-yyyy").format(c.getDayStart()));
            txtBill.append("\n+Ngay tra: " + new SimpleDateFormat("dd-MM-yyyy").format(c.getDayEnd()));
            compensation = updateFailureDetailText(c);
            txtBill.append("\n+Thanh tien: " + (c.getTotalAmount() + compensation));
            totalAmount += c.getTotalAmount() + compensation;
        }
        float deposit = updateMortgageText();
        txtBill.append("\nTong tien: " + (totalAmount - deposit));
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        btnAddFailure = new javax.swing.JButton();
        btnUpdateFailure = new javax.swing.JButton();
        btnAddMortgage = new javax.swing.JButton();
        btnPrintBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Invoice");

        txtBill.setEditable(false);
        txtBill.setColumns(20);
        txtBill.setRows(5);
        txtBill.setText("\t\t    Hoa don");
        jScrollPane1.setViewportView(txtBill);

        btnAddFailure.setText("AddFailure");
        btnAddFailure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFailureActionPerformed(evt);
            }
        });

        btnUpdateFailure.setText("UpdateFailure");
        btnUpdateFailure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFailureActionPerformed(evt);
            }
        });

        btnAddMortgage.setText("AddMortgage");
        btnAddMortgage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMortgageActionPerformed(evt);
            }
        });

        btnPrintBill.setText("PrintBill");
        btnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(439, 439, 439))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAddFailure)
                .addGap(166, 166, 166)
                .addComponent(btnUpdateFailure)
                .addGap(177, 177, 177)
                .addComponent(btnAddMortgage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btnPrintBill)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFailure)
                    .addComponent(btnUpdateFailure)
                    .addComponent(btnAddMortgage)
                    .addComponent(btnPrintBill))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
        (new ConfirmFrm(bill, listCarRentalChoosed, listMortgageDetailChoosed, this)).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPrintBillActionPerformed

    private void btnAddFailureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFailureActionPerformed
        (new CarReturnedFrm(1, listCarRentalChoosed, this)).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddFailureActionPerformed

    private void btnUpdateFailureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFailureActionPerformed
        (new CarReturnedFrm(2, listCarRentalChoosed, this)).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdateFailureActionPerformed

    private void btnAddMortgageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMortgageActionPerformed
        if(this.GDMortgage != null){
            this.GDMortgage.setVisible(true);
            this.setVisible(false);
        }
        else{
            try {
                this.GDMortgage = new MortgageFrm(bill, this);
                this.GDMortgage.setVisible(true);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(InvoiceFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddMortgageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFailure;
    private javax.swing.JButton btnAddMortgage;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JButton btnUpdateFailure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtBill;
    // End of variables declaration//GEN-END:variables
}
